// This file is auto generated by the protocol-buffers compiler

/* eslint-disable quotes */
/* eslint-disable indent */
/* eslint-disable no-redeclare */
/* eslint-disable camelcase */

// Remember to `npm install --save protocol-buffers-encodings`
var encodings = require('protocol-buffers-encodings')
var varint = encodings.varint
var skip = encodings.skip

var State = exports.State = {
  buffer: true,
  encodingLength: null,
  encode: null,
  decode: null
}

defineState()

function defineState () {
  var FeedState = State.FeedState = {
    buffer: true,
    encodingLength: null,
    encode: null,
    decode: null
  }

  defineFeedState()

  function defineFeedState () {
    var enc = [
      encodings.bytes
    ]

    FeedState.encodingLength = encodingLength
    FeedState.encode = encode
    FeedState.decode = decode

    function encodingLength (obj) {
      var length = 0
      if (!defined(obj.key)) throw new Error("key is required")
      var len = enc[0].encodingLength(obj.key)
      length += 1 + len
      if (!defined(obj.state)) throw new Error("state is required")
      var len = enc[0].encodingLength(obj.state)
      length += 1 + len
      return length
    }

    function encode (obj, buf, offset) {
      if (!offset) offset = 0
      if (!buf) buf = Buffer.allocUnsafe(encodingLength(obj))
      var oldOffset = offset
      if (!defined(obj.key)) throw new Error("key is required")
      buf[offset++] = 10
      enc[0].encode(obj.key, buf, offset)
      offset += enc[0].encode.bytes
      if (!defined(obj.state)) throw new Error("state is required")
      buf[offset++] = 18
      enc[0].encode(obj.state, buf, offset)
      offset += enc[0].encode.bytes
      encode.bytes = offset - oldOffset
      return buf
    }

    function decode (buf, offset, end) {
      if (!offset) offset = 0
      if (!end) end = buf.length
      if (!(end <= buf.length && offset <= buf.length)) throw new Error("Decoded message is not valid")
      var oldOffset = offset
      var obj = {
        key: null,
        state: null
      }
      var found0 = false
      var found1 = false
      while (true) {
        if (end <= offset) {
          if (!found0 || !found1) throw new Error("Decoded message is not valid")
          decode.bytes = offset - oldOffset
          return obj
        }
        var prefix = varint.decode(buf, offset)
        offset += varint.decode.bytes
        var tag = prefix >> 3
        switch (tag) {
          case 1:
          obj.key = enc[0].decode(buf, offset)
          offset += enc[0].decode.bytes
          found0 = true
          break
          case 2:
          obj.state = enc[0].decode(buf, offset)
          offset += enc[0].decode.bytes
          found1 = true
          break
          default:
          offset = skip(prefix & 7, buf, offset)
        }
      }
    }
  }

  var enc = [
    FeedState
  ]

  State.encodingLength = encodingLength
  State.encode = encode
  State.decode = decode

  function encodingLength (obj) {
    var length = 0
    if (defined(obj.states)) {
      for (var i = 0; i < obj.states.length; i++) {
        if (!defined(obj.states[i])) continue
        var len = enc[0].encodingLength(obj.states[i])
        length += varint.encodingLength(len)
        length += 1 + len
      }
    }
    return length
  }

  function encode (obj, buf, offset) {
    if (!offset) offset = 0
    if (!buf) buf = Buffer.allocUnsafe(encodingLength(obj))
    var oldOffset = offset
    if (defined(obj.states)) {
      for (var i = 0; i < obj.states.length; i++) {
        if (!defined(obj.states[i])) continue
        buf[offset++] = 10
        varint.encode(enc[0].encodingLength(obj.states[i]), buf, offset)
        offset += varint.encode.bytes
        enc[0].encode(obj.states[i], buf, offset)
        offset += enc[0].encode.bytes
      }
    }
    encode.bytes = offset - oldOffset
    return buf
  }

  function decode (buf, offset, end) {
    if (!offset) offset = 0
    if (!end) end = buf.length
    if (!(end <= buf.length && offset <= buf.length)) throw new Error("Decoded message is not valid")
    var oldOffset = offset
    var obj = {
      states: []
    }
    while (true) {
      if (end <= offset) {
        decode.bytes = offset - oldOffset
        return obj
      }
      var prefix = varint.decode(buf, offset)
      offset += varint.decode.bytes
      var tag = prefix >> 3
      switch (tag) {
        case 1:
        var len = varint.decode(buf, offset)
        offset += varint.decode.bytes
        obj.states.push(enc[0].decode(buf, offset, offset + len))
        offset += enc[0].decode.bytes
        break
        default:
        offset = skip(prefix & 7, buf, offset)
      }
    }
  }
}

function defined (val) {
  return val !== null && val !== undefined && (typeof val !== 'number' || !isNaN(val))
}
